### PR TITLE
[IMP] l10n_us_account_profile 0.0.2

### PR DESCRIPTION
**Pull request by max3903**
#5 

Depends on:
- [x] #8 
- [x] https://github.com/OCA/account-payment/pull/136

### CODE REVIEW

**Comment by lasley** [comment]
@max3903 - looks like tests are failing

**Comment by max3903** [comment]
@lasley This PR depends on all the others and will need to be reviewed at the end.

**Review by bodedra — APPROVED** [review]
LGTM. :+1:

**Review by mgosai — APPROVED** [review]
Good.

**Review by smangukiya — COMMENTED** [review]
Looks good to go!

**Pull request merged**
