### PR TITLE
[17.0][MIG] l10n_us_mis_financial_report: Migration to 17.0

### PR DESCRIPTION
**Pull request by christian-ramos-tecnativa**
Depends on PR:https://github.com/OCA/account-financial-reporting/pull/1231

### CODE REVIEW

**Comment by christian-ramos-tecnativa** [comment]
Merged
- [X] https://github.com/OCA/account-financial-reporting/pull/1231

**Review by Daniel-Melian — COMMENTED** [review]
Functionally reviewed. LGTM!

**Comment by AinohaBH** [comment]
Functionally reviewed. LGTM!

**Review by AinohaBH — APPROVED** [review]

**Review by Daniel-Melian — APPROVED** [review]

**Comment by christian-ramos-tecnativa** [comment]
Can you give us a hand here @max3903 @pedrobaeza ?

**Review by pedrobaeza — APPROVED** [review]
/ocabot migration l10n_us_mis_financial_report
/ocabot merge nobump

**Pull request merged**
