### PR TITLE
[13.0][MIG] l10n_us_form_1099

### LINKED ISSUE #46: Migration to version 13.0
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0

# Modules to migrate

- [ ] account_banking_ach_base
- [ ] account_banking_ach_credit_transfer
- [ ] account_banking_ach_direct_debit
- [ ] l10n_us_account_profile
- [ ] l10n_us_form_1099 - By @murtuzasaleh in #51 
- [ ] l10n_us_gaap - By @JoanSForgeFlow in #53

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

### PR DESCRIPTION
**Pull request by murtuzasaleh**
Manage 1099 Types and Suppliers

### CODE REVIEW

**Review by max3903 — APPROVED** [review]

**Review by smangukiya — APPROVED** [review]
Code LGTM. not tested.

**Comment by max3903** [comment]
@moylop260 Do you have any suggestions to avoid the sql injection error?

**Comment by moylop260** [comment]
Hi @max3903 
IMHO this is a valid case to use args where the variables are "privates" (no user input)
I will create a PR to pylint-odoo in order to consider this case

**Comment by moylop260** [comment]
Fixing from:
 - https://github.com/OCA/pylint-odoo/pull/268

**Review by bodedra — APPROVED** [review]
LGTM :+1:

**Review by HviorForgeFlow — CHANGES_REQUESTED** [review]
:red_circle: travis

Add pylint sql-injection line to avoid that error.

**Comment by HviorForgeFlow** [comment]
Hello @murtuzasaleh, let travis :green_heart: please

**Pull request merged**
