### PR TITLE
[12.0][MIG] account_banking_ach_direct_debit

### PR DESCRIPTION
**Pull request by max3903**

### CODE REVIEW

**Review by thinkwelltwd — APPROVED** [review]

**Comment by murtuzasaleh** [comment]
@max3903 Can you please review this PR.

**Comment by murtuzasaleh** [comment]
Depends on #40 and #https://github.com/OCA/bank-payment/pull/533

**Comment by max3903** [comment]
@murtuzasaleh Can you rebase?

**Comment by murtuzasaleh** [comment]
> @murtuzasaleh Can you rebase?

Done

**Comment by max3903** [comment]
@murtuzasaleh Can you fix the Runbot warning?
https://runbot.odoo-community.org/runbot/static/build/3377437-39-a21498/logs/job_20_test_all.txt

**Comment by murtuzasaleh** [comment]
> @murtuzasaleh Can you fix the Runbot warning?
> https://runbot.odoo-community.org/runbot/static/build/3377437-39-a21498/logs/job_20_test_all.txt

Done

**Pull request merged**
