### PR TITLE
[16.0][MIG] l10n_us_account_routing

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**
Standard Migration

@ForgeFlow

### CODE REVIEW

**Review by max3903 — APPROVED** [review]

**Review by ChrisOForgeFlow — APPROVED** [review]
LGTM

**Comment by JordiBForgeFlow** [comment]
@max3903 Could you please merge this one?

**Comment by JordiBForgeFlow** [comment]
@max3903 Thanks!

**Pull request merged**
