### PR TITLE
[11.0][MIG] l10n_us_account_profile

### PR DESCRIPTION
**Pull request by murtuzasaleh**
#17 

- [x] Depends on #35

### CODE REVIEW

**Review by Swapnesh-SerpentCS — APPROVED** [review]

**Comment by Swapnesh-SerpentCS** [comment]
It seems to have different error logs in Travis and OCA Runbot.

Travis fails because of `account_payment_batch_process` from account-payment but it is already there on OCA dependency list



Runbot is failing because of l10n_us_check_writing_address (Which is correct as it is not merged yet https://github.com/OCA/l10n-usa/pull/31)

Screenshot from 2019-06-13 17-40-27



Not sure if this is expected here (Cc @pedrobaeza )


Edit: To be followed after https://github.com/OCA/l10n-usa/pull/35

**Comment by max3903** [comment]
@murtuzasaleh Can you rebase and add `account_banking_reconciliation` from https://github.com/OCA/account-reconcile in the dependency?

**Comment by murtuzasaleh** [comment]
> @murtuzasaleh Can you rebase and add `account_banking_reconciliation` from https://github.com/OCA/account-reconcile in the dependency?

Done

**Comment by max3903** [comment]
@murtuzasaleh `partner_daytopay` has been renamed `partner_time_to_pay`.

**Review by max3903 — APPROVED** [review]

**Pull request merged**
