### PR TITLE
[16.0] [MIG] l10n_us_partner_legal_number

### PR DESCRIPTION
**Pull request by lk-eska**

### CODE REVIEW

**Review by max3903 — APPROVED** [review]

**Comment by ChrisOForgeFlow** [comment]
@lk-eska can you rebase please?

**Comment by lk-eska** [comment]
I think it's all good now.

**Review by ronny-montano — APPROVED** [review]

**Comment by JordiBForgeFlow** [comment]
@dreispt Can you merge this one? There's a chain of PR's depending on this one to merge.

**Comment by JordiBForgeFlow** [comment]
@max3903 Could you please merge?

**Pull request merged**
