### PR TITLE
[17.0][MIG] l10n_us_partner_legal_number

### PR DESCRIPTION
**Pull request by JordiMForgeFlow**

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
Code review LGTM

**Comment by JordiMForgeFlow** [comment]
Hi @max3903 

Could we get a review and merge this one? It is generating the requirements.txt file and it creates conflicts with other PRs that are also doing the same for V17 like https://github.com/OCA/l10n-usa/pull/137

**Review by JordiBForgeFlow — APPROVED** [review]

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by Abimael1321** [comment]
Functionally reviewed. LGTM!
I know that in previous versions it is not implemented, but as a suggestion, I would add some kind of notification if the legal ID number is the same in more than one contact, as is the case with the Tax ID.

**Review by Abimael1321 — APPROVED** [review]

**Review by JoanSForgeFlow — APPROVED** [review]

**Comment by JordiMForgeFlow** [comment]
@OCA/local-usa-maintainers could we get a merge here? :)

**Pull request merged**
