### PR TITLE
[Add][13.0][MIG] account_banking_ach_base

### PR DESCRIPTION
**Pull request by Chanakya-SerpentCS**

### CODE REVIEW

**Comment by bodedra** [comment]
@Chanakya-SerpentCS Can you make CI happy? Also preserve commit history. Ref: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0

**Comment by Chanakya-SerpentCS** [comment]
Travis is failed because of l10n_us_form_1099 module. So created PR https://github.com/OCA/l10n-usa/pull/68

**Comment by Chanakya-SerpentCS** [comment]
@bodedra  Please review this PR. CI is solved. Travis still shows error due to other module.

**Comment by bodedra** [comment]
Thank you @Chanakya-SerpentCS and what about preserve commit history?

**Comment by Chanakya-SerpentCS** [comment]
@bodedra  Please review. preserve commit history done.

**Review by bodedra — APPROVED** [review]
Functional reviewed. :+1:

**Pull request closed without merging**
